### ISSUE TITLE
Crash on Start

### ISSUE THREAD

**Issue by iMonZ** [TASVideos/BizHawk-Prereqs#6]
Getthing this crash on Start(Windows10 Version 20H2):
`System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at XInputGetState(UInt32 , _XINPUT_STATE* )
   at SlimDX.XInput.Controller.get_IsConnected()
   at BizHawk.Client.EmuHawk.GamePad360.Initialize()
   at BizHawk.Client.EmuHawk.DirectInputAdapter.FirstInitAll(IntPtr mainFormHandle)
   at BizHawk.Client.EmuHawk.MainForm..ctor(String[] args)
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)`

**Comment by geofrey** [comment]
Wait, what was the fix??

**Comment by YoshiRulz** [comment]
Probably just need to restart Windows after the installer is finished. See TASVideos/BizHawk#2537 and maybe TASVideos/BizHawk#2447.
